version: '3'
tasks:
  build:
    desc: Build the wpks-ls binary
    cmds:
      - go build -o bin/wpks-ls ./cmd/wpks-ls
    sources:
      - cmd/wpks-ls/**/*.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/wpks-ls
  test:
    desc: Run all Go tests
    cmds:
      - go tool gotestsum --format=testdox ./...
  lint:
    desc: Run all Go linters
    cmds:
      - go tool golangci-lint run  ./...
